- name: Create and start GlusterFS distributed volume
  hosts: worker-01
  become: yes
  tasks:
    - name: Create directories on all workers for GlusterFS bricks
      delegate_to: "{{ item }}"
      become: yes
      loop: "{{ groups['workers'] }}"
      file:
        path: /mnt/simulation_data/gfs
        state: directory
        mode: '0777'

    - name: Create GlusterFS volume (distributed across all workers)
      shell: >
        gluster volume create glustervol
        {% for worker in groups['workers'] %}
        {{ hostvars[worker].ansible_host }}:/mnt/simulation_data/gfs
        {% endfor %}
        force
      args:
        executable: /bin/bash
        creates: /var/lib/glusterd/vols/glustervol


    - name: Start GlusterFS volume
      shell: gluster volume start glustervol
      args:
        creates: /var/lib/glusterd/vols/glustervol/run
