- name: Mount GlusterFS volume on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Install GlusterFS client (if not already)
      apt:
        name: glusterfs-client
        state: present

    - name: Create mount point
      file:
        path: /mnt/qasm_shared
        state: directory
        mode: '0777'

    - name: Mount GlusterFS volume
      mount:
        src: "{{ hostvars['worker-01'].ansible_host }}:/glustervol"
        path: /mnt/qasm_shared
        fstype: glusterfs
        opts: defaults,_netdev
        state: mounted

    - name: Make mount persistent
      lineinfile:
        path: /etc/fstab
        line: "{{ hostvars['worker-01'].ansible_host }}:/glustervol /mnt/qasm_shared glusterfs defaults,_netdev 0 0"
        state: present