- name: Install Qiskit on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Install Qiskit with Aer support
      pip:
        name:
          - qiskit
          - qiskit-aer
        state: present
