- name: Deploy MinIO distributed service across worker nodes
  hosts: workers
  become: yes
  tasks:
    - name: Remove old minio service file
      file:
        path: /etc/systemd/system/minio.service
        state: absent

    - name: Copy templated minio.service
      template:
        src: templates/minio.service.j2
        dest: /etc/systemd/system/minio.service
        mode: '0644'

    - name: Reload systemd to apply new service
      systemd:
        daemon_reload: yes

    - name: Enable and start MinIO service
      systemd:
        name: minio
        enabled: yes
        state: restarted
