- name: Install Dask and dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install Dask with distributed support
      pip:
        name: 
          - "dask[distributed]"
          - "bokeh>=3.1.0"
        state: present

    - name: Install other useful Python packages
      pip:
        name:
          - distributed
          - numpy
          - pandas
          - scikit-learn
        state: present
