- name: Dask Scheduler service on management-node
  hosts: management
  become: yes
  tasks:
    - name: Create Dask scheduler systemd unit
      copy:
        dest: /etc/systemd/system/dask-scheduler.service
        content: |
          [Unit]
          Description=Dask Scheduler
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/dask-scheduler
          Restart=always
          User=ubuntu
          WorkingDirectory=/home/ubuntu

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start scheduler service
      systemd:
        name: dask-scheduler
        enabled: yes
        state: started

- name: Dask Worker services on all workers
  hosts: workers
  become: yes
  tasks:
    - name: Create Dask worker systemd unit
      copy:
        dest: /etc/systemd/system/dask-worker.service
        content: |
          [Unit]
          Description=Dask Worker
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/local/bin/dask-worker {{ hostvars['management-node'].ansible_host }}:8786
          Restart=always
          User=ubuntu
          WorkingDirectory=/home/ubuntu

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start worker service
      systemd:
        name: dask-worker
        enabled: yes
        state: started
