- name: Install and run Prometheus server
  hosts: management
  become: yes
  vars:
    prometheus_targets: |
      - {{ hostvars['worker-01'].ansible_host }}:9100
      - {{ hostvars['worker-02'].ansible_host }}:9100
      - {{ hostvars['worker-03'].ansible_host }}:9100
      - {{ hostvars['worker-04'].ansible_host }}:9100
      - {{ hostvars['management-node'].ansible_host }}:9100
  tasks:
    - name: Create Prometheus user
      user:
        name: prometheus
        shell: /usr/sbin/nologin

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Move Prometheus binaries
      shell: |
        mv /opt/prometheus-2.52.0.linux-amd64/prometheus /usr/local/bin/prometheus
        mv /opt/prometheus-2.52.0.linux-amd64/promtool /usr/local/bin/promtool
      args:
        creates: /usr/local/bin/prometheus

    - name: Create Prometheus config directory
      file:
        path: /etc/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Template Prometheus config file
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          User=prometheus
          Group=prometheus
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.listen-address=":9090" \
            --web.enable-lifecycle

          [Install]
          WantedBy=multi-user.target

    - name: Create data directory for Prometheus
      file:
        path: /var/lib/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart Prometheus service
      systemd:
        name: prometheus
        state: restarted
