---
- name: Install Podman & Ansible on All Nodes
  hosts: all
  become: true
  tasks:

    - name: Update package cache
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install Required Packages (RHEL-based)
      dnf:
        name:
          - python3
          - python3-pip
          - curl
          - git
          - podman
          - ansible
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure Podman is set up as a Docker alternative
      shell: "ln -s /usr/bin/podman /usr/bin/docker || true"
      args:
        creates: /usr/bin/docker

    - name: Enable Podman Service (Optional for Systemd-managed Containers)
      systemd:
        name: podman
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

    - name: Verify Podman Installation
      command: podman --version
      register: podman_version_output
      changed_when: false

    - debug:
        msg: "Podman Installed: {{ podman_version_output.stdout }}"

    - name: Install WGET for the systems
      dnf:
        name: wget
        state: present

    - name: Ensure BASH is the default shell for all users
      user: 
        name: "{{ ansible_user }}"
        shell: /bin/bash
