- name: Common system setup on all nodes
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes

    - name: Install common system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - build-essential
          - htop
          - git
          - curl
          - unzip
        state: present

    - name: Ensure Python's pip is the latest version
      pip:
        name: pip
        state: latest
