- name: Install Miniconda in all the machines
  hosts: all
  become: true
  tasks:
    - name: Ensure required packages are installed 
      yum: 
        name: 
          - wget
          - bzip2
        state: present
    
    - name: Download Miniconda for the VMs
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/miniconda.sh
        mode: '0755'

    - name: Install Miniconda
      shell: |
        bash /tmp/miniconda.sh -b -p /opt/miniconda
      args: 
        creates: /opt/miniconda/

    - name: Update PATH for Conda
      lineinfile:
        path: /etc/environment
        line: 'PATH="/opt/miniconda/bin:{{ ansible_env.PATH }}"'
        regexp: '^PATH='
        state: present
    
    - name: Initialize Conda for all users
      shell: |
        /opt/miniconda/bin/conda init
      args:
        executable: /bin/bash

    - name: Clean up installer
      file:
        path: /tmp/miniconda.sh
        state: absent

    - name: Update Conda to the latest version
      shell: |
        /opt/miniconda/bin/conda update -n base -c defaults conda -y
      args:
        executable: /bin/bash
