---
- name: Download MNISQ Dataset to Worker Nodes
  hosts: workers
  become: true
  tasks:
    - name: Ensure dataset directory exists
      file:
        path: /mnt/simulation_data/qasm_circuits
        state: directory
        mode: '0777'

    - name: Download QASM files from GitHub
      shell: |
        wget -r -np -nH --cut-dirs=1 -R "index.html*" -P /mnt/simulation_data/qasm_circuits https://github.com/mnisq/dataset/raw/main/qasm_files/
      args:
        chdir: /mnt/simulation_data/qasm_circuits
      register: download_result
      ignore_errors: yes

    - name: Print download result
      debug:
        msg: "{{ download_result.stdout }}"